### ISSUE TITLE
FS2: Logger doesn't print

### ISSUE THREAD

**Issue by emaysyuk** [LEGO/woof#237]
Can anybody tell why logger doesn't print from inside of FS2 Stream ([here](https://github.com/emaysyuk/scala-woof-logger-issue/blob/main/src/main/scala/com/may/main.scala#L34) and [here](https://github.com/emaysyuk/scala-woof-logger-issue/blob/main/src/main/scala/com/may/main.scala#L42))?

I've prepared a simple project to illustrate the problem.

https://github.com/emaysyuk/scala-woof-logger-issue

Looks like the problem in [DefaultLogger#logToOutputs](https://github.com/LEGO/woof/blob/main/modules/core/shared/src/main/scala/org/legogroup/woof/DefaultLogger.scala#L48), the logger cannot summon `Local[IO, List[(String, String)]]` but I don't see why because no errors are thrown.

**Comment by hejfelix** [comment]
Maybe I'm missing something, but isn't this an unused value in these lines:

https://github.com/emaysyuk/scala-woof-logger-issue/blob/067b522b6c6dae801b47eb950d159756bfffd36e/src/main/scala/com/may/main.scala#L32C1-L35C19

i.e. you're throwing away the value from the for yield:

```scala
...
      .flatMap { httpServer =>
        for {
          given Logger[IO] <- DefaultLogger.makeIo(Output.fromConsole)
          _ <- Logger[IO].warn("Before exception") // TODO: doesn't print anything
        } yield ()  // this value is not saved or returned from the function?
        Stream.eval(httpServer.useForever).concurrently {
          throw new RuntimeException("Catch me and log to console")
        }
      }
```

I'll try to reproduce it

**Comment by hejfelix** [comment]
This works well on my end:

```scala
//> using dep co.fs2::fs2-core::3.10.2
//> using dep org.legogroup::woof-core::0.7.0

import cats.effect.unsafe.implicits.global
import org.legogroup.woof.{given, *}
import cats.effect.IO
import fs2.Stream
import Logger.*
given Filter = Filter.everything
given Printer = NoColorPrinter()

@main
def main(): Unit =
  val program = for
    given Logger[IO] <- DefaultLogger.makeIo(Output.fromConsole[IO])
    _ <- Logger[IO].info("Hello, world!")
    _ <- logInStream.withLogContext("stream" -> "log")
  yield ()

  program.unsafeRunSync()

def logInStream(using Logger[IO]): IO[Unit] =
  Stream
    .emits(1 to 10)
    .evalMap(i => Logger[IO].info(s"Processing $i"))
    .compile
    .drain
```

**Comment by hejfelix** [comment]
Oh yeah, on the `handleError` you're again giving it an unused value. The type of `handleError` is:


```
  def handleError[B >: A](f: Throwable => B): IO[B] =
    handleErrorWith[B](t => IO.pure(f(t)))
 ```
 
 you want to use `handleErrorWith(...)` if you want side effects. So looks to me like you have unused effect values in both cases.

**Comment by hejfelix** [comment]
Made a pull request to demonstrate: https://github.com/emaysyuk/scala-woof-logger-issue/pull/1
