### ISSUE TITLE
Create Guides

### ISSUE THREAD

**Issue by MartinNygaardSchacht** [LEGO/woof#68]

**Comment by hejfelix** [comment]
Hi Martin,

Would this be the same as in https://github.com/LEGO/woof/issues/3 ? We are working on these self-contained examples as we speak :)

**Comment by MartinNygaardSchacht** [comment]
I am very sorry - I was playing around in GitHub Projecs, and somehow I ended up createing this issue on this Repo. I have nothing to do with the roof repo. ;-)
