### ISSUE TITLE
Consider publishing for scala-native

### ISSUE THREAD

**Issue by lavrov** [LEGO/woof#92]
There has been progress in scala-native world recently. It got [runtime](https://github.com/armanbilge/epollcat) for cats-effect. As this library is built on cats-effect, would it be possible to add support for scala-native?

**Comment by hejfelix** [comment]
As for the details:

* slf4j won't be compatible 
* Core can be cross built
* Http4s can be cross built 

I'm not sure how the release and packaging stuff works for scala native – hopefully it's as easy as the other targets?

**Comment by kubukoz** [comment]
The release process should work like the usual (just like JS) :)
